//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CarFinderSvcDemoEntities : DbContext
    {
        public CarFinderSvcDemoEntities()
            : base("name=CarFinderSvcDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyStyle> BodyStyles { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<DriveType> DriveTypes { get; set; }
        public virtual DbSet<EngineFuel> EngineFuels { get; set; }
        public virtual DbSet<EnginePosition> EnginePositions { get; set; }
        public virtual DbSet<EngineType> EngineTypes { get; set; }
        public virtual DbSet<Make> Makes { get; set; }
        public virtual DbSet<TransmissionType> TransmissionTypes { get; set; }
    
        public virtual ObjectResult<CarEngineSizecc_Result> CarEngineSizecc(string engine_cc)
        {
            var engine_ccParameter = engine_cc != null ?
                new ObjectParameter("engine_cc", engine_cc) :
                new ObjectParameter("engine_cc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CarEngineSizecc_Result>("CarEngineSizecc", engine_ccParameter);
        }
    
        public virtual ObjectResult<CarsOrderedByWeight_Result> CarsOrderedByWeight()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CarsOrderedByWeight_Result>("CarsOrderedByWeight");
        }
    
        public virtual ObjectResult<CarsOver300HP_Result> CarsOver300HP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CarsOver300HP_Result>("CarsOver300HP");
        }
    
        public virtual ObjectResult<CarsWeightUnder2000kg_Result> CarsWeightUnder2000kg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CarsWeightUnder2000kg_Result>("CarsWeightUnder2000kg");
        }
    
        public virtual ObjectResult<GetAllSuvs_Result> GetAllSuvs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllSuvs_Result>("GetAllSuvs");
        }
    
        public virtual ObjectResult<string> GetCarMakesForYear(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetCarMakesForYear", yearParameter);
        }
    
        public virtual ObjectResult<string> GetCarModelsYearMake(string year, string make)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var makeParameter = make != null ?
                new ObjectParameter("make", make) :
                new ObjectParameter("make", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetCarModelsYearMake", yearParameter, makeParameter);
        }
    
        public virtual ObjectResult<GetCarYearMakeModelTrim_Result> GetCarYearMakeModelTrim(string year, string make, string model, string trim)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var makeParameter = make != null ?
                new ObjectParameter("make", make) :
                new ObjectParameter("make", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            var trimParameter = trim != null ?
                new ObjectParameter("trim", trim) :
                new ObjectParameter("trim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCarYearMakeModelTrim_Result>("GetCarYearMakeModelTrim", yearParameter, makeParameter, modelParameter, trimParameter);
        }
    
        public virtual ObjectResult<string> GetModelTrimYearMakeModel(string year, string make, string model)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var makeParameter = make != null ?
                new ObjectParameter("make", make) :
                new ObjectParameter("make", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("model", model) :
                new ObjectParameter("model", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetModelTrimYearMakeModel", yearParameter, makeParameter, modelParameter);
        }
    
        public virtual ObjectResult<string> GetUniqueCarMake()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUniqueCarMake");
        }
    
        public virtual ObjectResult<string> GetUniqueCarMakeForYear(string year)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUniqueCarMakeForYear", yearParameter);
        }
    
        public virtual ObjectResult<string> GetUniqueCarModel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUniqueCarModel");
        }
    
        public virtual ObjectResult<string> GetUniqueModelYears()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUniqueModelYears");
        }
    
        public virtual ObjectResult<string> GetUniqueTrimLevels()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUniqueTrimLevels");
        }
    
        public virtual ObjectResult<MidEngineCars_Result> MidEngineCars()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MidEngineCars_Result>("MidEngineCars");
        }
    
        public virtual ObjectResult<OrderByHorsePower_Result> OrderByHorsePower()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderByHorsePower_Result>("OrderByHorsePower");
        }
    
        public virtual ObjectResult<OrderByHPOver300AndWeight_Result> OrderByHPOver300AndWeight()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderByHPOver300AndWeight_Result>("OrderByHPOver300AndWeight");
        }
    
        public virtual ObjectResult<WeightUnder2000Least300HP_Result> WeightUnder2000Least300HP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WeightUnder2000Least300HP_Result>("WeightUnder2000Least300HP");
        }
    
        public virtual ObjectResult<string> GetAllYearsofCars()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAllYearsofCars");
        }
    }
}
